name = "Preliminary Art Form"
author = "LorianStudio"
version = "26.2-A1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0903c41e9842ee9fb0fd81b865c5ebb52d6120b4f75e8974586c9c207eb94909"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
