beeInformationStyle = "ICONS"
itemDurabilityStyle = "FORMATED_VALUES"
enchantmentsStyle = "COLORED_TEXT"
enchantmentsSorted = true
enchantmentsRomanNumerals = true
foodNutritionStyle = "ICONS"
effectsStyle = "COLORED_TEXT"
effectsShowIcons = true
effectsShowModifiers = true
bucketEntityStyle = "VISIBLE_WITH_MODEL"
bucketEntityRotate = true
bucketEntityAnimate = true
bannerPatternStyle = "COLORED_TEXT"
bannerPatternShowIcons = true
mapStyle = "COLORED_TEXT"
mapShowPreview = true
mapShowDimension = false
mapShowCoordinates = false
paintingStyle = "COLORED_TEXT"
paintingShowPreview = true
paintingShowAuthor = true
armorTrimStyle = "COLORED_TEXT"
armorTrimShowIcons = true
itemIdentifierStyle = "ALWAYS_VISIBLE"
showModName = true
removeEmptyLines = true
removeCreativeTabNames = true
durationFormat = "TIME"
